# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/venus/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),venus)

$(call add-radio-file-sha1-checked,radio/abl.img,d2899faf48be2bd5d10945de808c1085e9517963)
$(call add-radio-file-sha1-checked,radio/aop.img,003fd964c710d18edda37792299cbd3a5ea4db03)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b47aafe1fa4628d35b3995a1b24856135025a7a7)
$(call add-radio-file-sha1-checked,radio/cpucp.img,20fba142e807f73983b464258e0517e027015025)
$(call add-radio-file-sha1-checked,radio/devcfg.img,32e3458d1aa977e87a09e8e0428371aaf4c7ead0)
$(call add-radio-file-sha1-checked,radio/dsp.img,8b27181b72bcc6cc003e5c21bac38993e7015995)
$(call add-radio-file-sha1-checked,radio/featenabler.img,78265b25518b109bba9a1b334f5f6836de0ef44c)
$(call add-radio-file-sha1-checked,radio/hyp.img,4ee7d7eaa1d14846a8142bcba17d427ddfc3e791)
$(call add-radio-file-sha1-checked,radio/imagefv.img,33ffafbba6b53edf776764f92cd54dd5c5d62d10)
$(call add-radio-file-sha1-checked,radio/keymaster.img,45325ff64cee0e16cd36a0df8481bbaac4a1060c)
$(call add-radio-file-sha1-checked,radio/modem.img,61ee3bca0e206baa9e07c4140f60271c18eb116a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,68c2080328b0eb1443df0fe6d771821ef149199f)
$(call add-radio-file-sha1-checked,radio/shrm.img,0990fd68eeac2d051a5cd901d8a9e2708726e7f4)
$(call add-radio-file-sha1-checked,radio/tz.img,7823bb4a23423be8ce9bfdb1099b253d0fa39aee)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,e77e4622246ab5ea532e8c84d4a90fce3f480e19)
$(call add-radio-file-sha1-checked,radio/xbl.img,a3bd26fe9d9c5603d07ffd46aea48965bed32849)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,8dc6418a27b028dc503474301d59056c95038959)

endif
