# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/venus/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),venus)

$(call add-radio-file-sha1-checked,radio/abl.img,5ec19dcb96b02c2302f942ed2c15edbb03ba6e14)
$(call add-radio-file-sha1-checked,radio/aop.img,443e79b7f2f94df2653cf08a66a00432faf86232)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,0e9c6d61a69843d8e2c02c7d17f34b9d61d11c3e)
$(call add-radio-file-sha1-checked,radio/cpucp.img,9edc88e92e71c10b9333b27a7fd4038300a96b27)
$(call add-radio-file-sha1-checked,radio/devcfg.img,df71097284831079d5d9d1934147865d99dc6ace)
$(call add-radio-file-sha1-checked,radio/dsp.img,453413b40e59bfbd20bcb03dce4e3538f0f04550)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ce3f307458372dc068ad7d4632fcf5829df6bfff)
$(call add-radio-file-sha1-checked,radio/hyp.img,5acae8e5df521ec07021941f0d728d95bb424f1e)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e9289152448de54fc81c19a86946c5112817bfbb)
$(call add-radio-file-sha1-checked,radio/keymaster.img,937ed3cf6d80d3537643a9f8370a5f1d11aad8e9)
$(call add-radio-file-sha1-checked,radio/modem.img,b3562073514305bf3ec2676dcb8617306ee46113)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ae06ccf4593581137d8328975a85e9dc1cf33405)
$(call add-radio-file-sha1-checked,radio/shrm.img,b41886b95d9f6679197d521c7adb69298f057d09)
$(call add-radio-file-sha1-checked,radio/tz.img,45499f1add2f7b616cafea5d2dda16a4e428f334)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,49ab5cb656fe9cb5c60ce606e9a6dd3632835698)
$(call add-radio-file-sha1-checked,radio/xbl.img,1e11be2f8696653dc2c5735b575542aaae958be4)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,7db11c644a85131898f9f53acc3ac842e7fc9131)

endif
